FROM vorontsovie/rmagick:alpine
ARG SEQLOGO_VERSION=1.3.2
RUN gem install sequence_logo -v "$SEQLOGO_VERSION"
WORKDIR /data
ENTRYPOINT ["sequence_logo"]
CMD ["--help"]
# docker run --rm --mount type=bind,src=$(pwd),dst=/data sequence_logo motif.pcm
